### ISSUE TITLE
Add "How to build and test locally" section

### ISSUE THREAD

**Issue by filfreire** [adidas/api-guidelines#10]
The `README.md` file could have these sections:
- "How to Build";
- "How to test locally";

So any contributor knows how to test the repository locally.

/cc @zdne @Amzani

**Comment by jesusjavierdediego** [comment]
I think the guidelines Core Principles [section](https://adidas.gitbook.io/api-guidelines/rest-api-guidelines/core-principles/testing) (landing page) already covers these topics.  I'll close this issue.
