### ISSUE TITLE
Guidelines for muti-value search filters

### ISSUE THREAD

**Issue by zwedoc** [adidas/api-guidelines#18]
* **I'm submitting a ...**
  - [X] feature request

* **What is the current behavior?**
While we have guidelines on how to request multiple fields or embedded resources, search request section does not consider multi-value filters. OpenAPI defines different serialization options so we could mention all of them or choose one format as preferred option: https://swagger.io/docs/specification/serialization/

* **What is the expected behavior?**
Search filter structures for multi-value attributes are mentioned in the search request section.

* **What is the motivation / use case for changing the behavior?**
I think it is always advisable to provide guidelines for complex search filters as it is a common user case for many APIs.

**Comment by jesusjavierdediego** [comment]
This feature belongs to OpenAPI 3. The issue was created when the API Guidelines supported only OpenAPI 2. The changes to consider OpenAPI 3 are done and it will be part of them. Thanks!
