### ISSUE TITLE
Could not parse https://unpkg.com/spectral:oas2: Forbidden 

### ISSUE THREAD

**Issue by Amzani** [adidas/api-guidelines#33]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

```
spectral lint ./demo-orderapi-v3.oas2.yaml -r ./api-guidelines/.spectral.yml
Could not parse https://unpkg.com/spectral:oas2: Forbidden
```

* **What is the expected behavior?**

Showing the potentials warnings / errors to validate the API Spec against the guidelines

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

node version: v12.16.1
spectral version: 5.2.0

**Comment by jesusjavierdediego** [comment]
a new example is provided in the next update of the guidelines.
The valid example is tested successfully:
```
$ spectral lint petstore.yaml 
OpenAPI 3.x detected
No results with a severity of 'error' or higher found!
```
Node version: 14.15.2
Spectral version: 5.8.0
