### ISSUE TITLE
Faulty Regex

### ISSUE THREAD

**Issue by rallyRussell** [adidas/api-guidelines#47]
https://github.com/adidas/api-guidelines/blob/d10e8a904372a0512a7245077a73d971fdc1411c/.spectral.yml#L87

It's dangerous to go alone! Take this:

`^[A-Z][a-z0-9]*(?:-[A-Z][a-z0-9]*)*$`

**Comment by cesareomacias** [comment]
Thank you for your suggestion @rallyRussell  but with your match we're not forcing to use hyphen after each segment and we're interested on that.
Regards.
