### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by 11100010** [adidas/api-guidelines#72]
nothing looks alive here.

**Comment by cesareomacias** [comment]
Hi,
No. This project is alive and running! 
Regards

**Comment by 11100010** [comment]
Hi cesareomacias,
Does adidas running support a public API? 
Or it only limits to its internal use. I can't find any information related to the public API, except this guidelines here.

**Comment by cesareomacias** [comment]
Hi,
No, It doesn't any public API supported.
Best.
