### ISSUE TITLE
Add .github templates for contributors

### ISSUE THREAD

**Issue by filfreire** [adidas/api-guidelines#8]
@zdne @Amzani @apidesigner 
Let's add Issue and Pull Request templates for both internal and external contributors to know how best to contribute to the API Guidelines:

Example: https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by zdne** [comment]
Thanks for swinging by! Feel free to open the PR with your proposal.

**Comment by Amzani** [comment]
Thanks @filfreire

**Comment by zdne** [comment]
Merged.
